#ANS1)

In [1]:
import numpy as np
arr=np.array(range(2,51,3))
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [2]:
#ANS2)
x=[]
i=0
while i<5:
    a=input()
    b=int(a)
    c=x.append(b)
    i+=1
y=[]    
j=0
while j<5:
    d=input()
    e=int(d)
    f=y.append(e)
    j+=1
    
arr1=np.array(x)
arr2=np.array(y)
arr1.sort()
arr2.sort()
print(arr1)
print(arr2)


56
35
6
88
64
86
57
48
65
95
[ 6 35 56 64 88]
[48 57 65 86 95]


In [3]:
#ANS3)

array=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
array
print(array.shape)
print(array.size)

(2, 6)
12


In [4]:
#ANS4)

array_1d = np.array([1,2,3,4,5])
print(array_1d.shape)
array_2d=array_1d[: , np.newaxis][1:5]
print(array_2d.shape)

(5,)
(4, 1)


In [5]:
#ANS5)
ayush=np.array([[1,2,3],[4,5,6],[7,8,9]])
garg=np.array([[11,12,13],[14,15,16],[17,18,19]])
print(np.vstack(ayush))
print(np.vstack(garg))
print(np.hstack(ayush))
print(np.hstack(garg))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


In [6]:
#ANS6)
app=(ayush)+(garg)
print(app)
np.where(5)

[[12 14 16]
 [18 20 22]
 [24 26 28]]


(array([0], dtype=int64),)